services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432